#!/bin/bash
#Ejemplo 1
mkdir prueba1
cp Main.class ./prueba1/Main.class
cd prueba1/
java Main ../ejemplos/Ejem1/ejem1.prog Ej1
javac Ej1.java
#Test ejemplo 1
java Ej1 5
echo "CORRECT: Resultado= 15"
java Ej1 1
echo "CORRECT: Resultado= 1"
java Ej1 2
echo "CORRECT: Resultado= 3"
java Ej1 10
echo "CORRECT: Resultado= 55"
cd ..
#Ejemplo 2
mkdir prueba2
cp Main.class ./prueba2/Main.class
cd prueba2/
java Main ../ejemplos/Ejem2/ejem2.prog Ej2
javac Ej2.java
#Test ejemplo 2
echo "TEST:"
java Ej2 10
echo "CORRECT:"
echo "Resultado= 0"
echo ""
echo "TEST:"
java Ej2 101
echo "CORRECT:"
echo "Salida 2"
echo "Resultado= 158"
echo ""
echo "TEST:"
java Ej2 127
echo "CORRECT:"
echo "Salida 1"
echo "Salida 2"
echo "Resultado= 223"
echo ""
echo "TEST:"
java Ej2 85
echo "CORRECT:"
echo "Salida 2"
echo "Resultado= 217"
echo ""
echo "TEST:"
java Ej2 356
echo "CORRECT:"
echo "Salida 2"
echo "Resultado= 749"
echo ""
echo "TEST:"
java Ej2 520
echo "CORRECT:"
echo "Resultado= 1046"
echo ""
echo "TEST:"
java Ej2 354
echo "Salida 1"
echo "Resultado= 703"
echo ""
echo "TEST:"
java Ej2 458
echo "CORRECT:"
echo "Salida 1"
echo "Salida 2"
echo "Resultado= 803"
echo ""
cd ..
#Ejemplo 3
mkdir prueba3
cp Main.class ./prueba3/Main.class
cd prueba3/
java Main ../ejemplos/Ejem3/ejem3.prog Ej3
javac Ej3.java
#Test ejemplo 3
echo "TEST:"
java Ej3 101
echo "CORRECT:"
echo "Salida 2"
echo "Resultado= 158"
echo ""
echo "TEST:"
java Ej3 127
echo "CORRECT:"
echo "Salida 1"
echo "Salida 2"
echo "Resultado= 223"
echo ""
echo "TEST:"
java Ej3 85
echo "CORRECT:"
echo "Salida 2"
echo "Resultado= 217"
echo ""
echo "TEST:"
java Ej3 356
echo "Salida 2"
echo "Resultado= 749"
echo ""
echo "TEST:"
java Ej3 520
echo "CORRECT:"
echo "Resultado= 1046"
echo ""
echo "TEST:"
java Ej3 354
echo "CORRECT:"
echo "Salida 1"
echo "Resultado= 703"
echo ""
java Ej3 458
echo "CORRECT:"
echo "Salida 1"
echo "Salida 2"
echo "Resultado= 803"
echo ""
cd ..
#Ejemplo 4
mkdir prueba4
cp Main.class ./prueba4/Main.class
cd prueba4/
java Main ../ejemplos/Ejem4/ejem4.prog Ej4
javac Ej4.java
#Test ejemplo 4
echo "TEST:"
java Ej4 luis
echo "CORRECT:"
echo "Hola luis"
echo "Resultado 1= -5"
echo "Resultado 2= 1"
echo "Resultado 3= 10"
echo "Resultado 4= 2"
echo "Resultado 5= 82"
echo "Resultado 6= 78"
echo "Resultado 7= 1000"
echo "Resultado 8 correcto"
echo "Resultado 9 correcto"
echo "Resultado 10 correcto"
echo "Resultado 11 correcto"
echo "Resultado 12 correcto"
echo ""
cd ..
#Ejemplo 5
mkdir prueba5
cp Main.class ./prueba5/Main.class
cd prueba5/
java Main ../ejemplos/Ejem5/ejem5.prog Ej5
javac Ej5.java
#Test ejemplo 5
#Si la suma de los dos ultimos numeros primos es mayor que el arg3 se termina el test.
#Saca todos los numeros primos por debajo del arg1
#Si el penultimo primo sacado multiplicado por un numero menor que arg1 y mayor que el ultimo primo es mayor que arg2 termina el test.
echo "TEST:"
java Ej5 1 1 1
echo "CORRECT:"
echo ""
echo "TEST:"
java Ej5 20 323 24
echo "CORRECT:"
echo "2 es un numero primo"
echo "3 tambien es un numero primo"
echo "5 es un numero primo"
echo "7 tambien es un numero primo"
echo "11 es un numero primo"
echo "13 tambien es un numero primo"
echo "17 es un numero primo"
echo "19 tambien es un numero primo"
echo ""
echo "TEST:"
java Ej5 18 323 24
echo "CORRECT:"
echo "2 es un numero primo"
echo "3 tambien es un numero primo"
echo "5 es un numero primo"
echo "7 tambien es un numero primo"
echo "11 es un numero primo"
echo "13 tambien es un numero primo"
echo "17 es un numero primo"
echo ""
echo "TEST:"
java Ej5 20 322 24
echo "CORRECT:"
echo "2 es un numero primo"
echo "3 tambien es un numero primo"
echo "5 es un numero primo"
echo "7 tambien es un numero primo"
echo "11 es un numero primo"
echo "13 tambien es un numero primo"
echo "17 es un numero primo"
echo ""
echo "TEST:"
java Ej5 20 323 23
echo "CORRECT:"
echo "2 es un numero primo"
echo "3 tambien es un numero primo"
echo "5 es un numero primo"
echo "7 tambien es un numero primo"
echo "11 es un numero primo"
echo "13 tambien es un numero primo"
echo ""
cd ..
#Ejemplo 6
mkdir prueba6
cp Main.class ./prueba6/Main.class
cd prueba6/
java Main ../ejemplos/Ejem6/ejem6.prog Ej6
javac Ej6.java
#Test ejemplo 6
#El test no tiene argumentos por lo que no se le puede pasar ningun valor.
#Hay 2 espacios en los resultados.
echo "TEST:"
java Ej6 
echo "CORRECT:"
echo "Punto A"
echo "Valor de i=  4"
echo "Punto B"
echo "Valor de i=  5"
echo "Punto C"
echo "Valor de i=  5"
echo "Punto D"
echo "Valor final de i=  5"
echo ""
cd ..
#Ejemplo 7
mkdir prueba7
cp Main.class ./prueba7/Main.class
cd prueba7/
java Main ../ejemplos/Ejem7/ejem7.prog Ej7
javac Ej7.java
#Test ejemplo 7
#El test no tiene argumentos por lo que no se le puede pasar ningun valor.
#Hay 2 espacios en los resultados.
echo "TEST:"
java Ej7 
echo "CORRECT:"
echo "Punto B"
echo "Valor de i=  4"
echo "Punto D"
echo "Valor final de i=  4"
echo ""
cd ..
#Ejemplo 8
mkdir prueba8
cp Main.class ./prueba8/Main.class
cd prueba8/
java Main ../ejemplos/Ejem8/ejem8.prog Ej8
javac Ej8.java
#Test ejemplo 8
#Hay 2 espacios en los resultados.
echo "TEST:"
java Ej8 0
echo "CORRECT:"
echo "Punto A"
echo "Valor de i=  4"
echo "Punto B"
echo "Valor de i=  5"
echo "Punto C"
echo "Valor de i=  5"
echo "Punto D"
echo "Valor final de i=  5"
echo ""
echo "TEST:"
java Ej8 1
echo "CORRECT:"
echo "Punto C"
echo "Valor de i=  4"
echo "Punto D"
echo "Valor final de i=  4"
echo ""
java Ej8 2
echo "CORRECT:"
echo "Punto D"
echo "Valor final de i=  4"
echo ""
cd ..
java Main ../ejemplos/Ejem8/ejem8.prog Ej8
java Main ejemplos/ErrLex1/errLex1.prog prog
java Main ejemplos/ErrLex2/errLex2.prog prog
java Main ejemplos/ErrSem1/errSem1.prog prog
java Main ejemplos/ErrSem2/errSem2.prog prog
java Main ejemplos/ErrSem3/errSem3.prog prog
java Main ejemplos/ErrSem4/errSem4.prog prog
java Main ejemplos/ErrSem5/errSem5.prog prog
java Main ejemplos/ErrSem6/errSem6.prog prog
java Main ejemplos/ErrSem7/errSem7.prog prog
java Main ejemplos/ErrSem8/errSem8.prog prog
java Main ejemplos/ErrSem9/errSem9.prog prog
java Main ejemplos/ErrSem10/errSem10.prog prog
java Main ejemplos/ErrSem11/errSem11.prog prog
java Main ejemplos/ErrSem12/errSem12.prog prog
java Main ejemplos/ErrSem13/errSem13.prog prog
java Main ejemplos/ErrSem14/errSem14.prog prog
java Main ejemplos/ErrSem15/errSem15.prog prog
java Main ejemplos/ErrSem16/errSem16.prog prog
java Main ejemplos/ErrSem17/errSem17.prog prog
java Main ejemplos/ErrSem18/errSem18.prog prog
java Main ejemplos/ErrSint1/errSint1.prog prog
java Main ejemplos/ErrSint2/errSint2.prog prog
java Main ejemplos/ErrSint3/errSint3.prog prog
java Main ejemplos/ErrSint4/errSint4.prog prog
