#!/bin/bash
#Ejemplo 1
mkdir prueba1
cp Main.class ./prueba1/Main.class
cd prueba1/
java Main ../ejemplos/Ejem1/ejem1.prog Ej1
javac Ej1.java
#Test ejemplo 1
java Ej1 5
echo "CORRECT: Resultado= 15"
java Ej1 1
echo "CORRECT: Resultado= 1"
java Ej1 2
echo "CORRECT: Resultado= 3"
java Ej1 10
echo "CORRECT: Resultado= 55"
cd ..
#Ejemplo 2
mkdir prueba2
cp Main.class ./prueba2/Main.class
cd prueba2/
java Main ../ejemplos/Ejem2/ejem2.prog Ej2
javac Ej2.java
#Test ejemplo 2
echo "TEST:"
java Ej2 10
echo "CORRECT:"
echo "Resultado= 0"
echo ""
echo "TEST:"
java Ej2 101
echo "CORRECT:"
echo "Salida 2"
echo "Resultado= 158"
echo ""
echo "TEST:"
java Ej2 127
echo "CORRECT:"
echo "Salida 1"
echo "Salida 2"
echo "Resultado= 223"
echo ""
echo "TEST:"
java Ej2 85
echo "CORRECT:"
echo "Salida 2"
echo "Resultado= 217"
echo ""
echo "TEST:"
java Ej2 356
echo "CORRECT:"
echo "Salida 2"
echo "Resultado= 749"
echo ""
echo "TEST:"
java Ej2 520
echo "CORRECT:"
echo "Resultado= 1046"
echo ""
echo "TEST:"
java Ej2 354
echo "Salida 1"
echo "Resultado= 703"
echo ""
echo "TEST:"
java Ej2 458
echo "CORRECT:"
echo "Salida 1"
echo "Salida 2"
echo "Resultado= 803"
echo ""
cd ..
#Ejemplo 3
mkdir prueba3
cp Main.class ./prueba3/Main.class
cd prueba3/
java Main ../ejemplos/Ejem3/ejem3.prog Ej3
javac Ej3.java
#Test ejemplo 3
cd ..
#Ejemplo 4
mkdir prueba4
cp Main.class ./prueba4/Main.class
cd prueba4/
java Main ../ejemplos/Ejem4/ejem4.prog Ej4
javac Ej4.java
#Test ejemplo 4
cd ..
#Ejemplo 5
mkdir prueba5
cp Main.class ./prueba5/Main.class
cd prueba5/
java Main ../ejemplos/Ejem5/ejem5.prog Ej5
javac Ej5.java
#Test ejemplo 5
cd ..
#Ejemplo 6
mkdir prueba6
cp Main.class ./prueba6/Main.class
cd prueba6/
java Main ../ejemplos/Ejem6/ejem6.prog Ej6
javac Ej6.java
#Test ejemplo 6
cd ..
#Ejemplo 7
mkdir prueba7
cp Main.class ./prueba7/Main.class
cd prueba7/
java Main ../ejemplos/Ejem7/ejem7.prog Ej7
javac Ej7.java
#Test ejemplo 7
cd ..
#Ejemplo 8
mkdir prueba8
cp Main.class ./prueba8/Main.class
cd prueba8/
java Main ../ejemplos/Ejem8/ejem8.prog Ej8
javac Ej8.java
#Test ejemplo 8
cd ..
